web/urls.py
from django.urls import path
from web import views

app_name="web"
urlpatterns = [
    path('',views.index,name="index"),
    path('testConnect/',views.testNginxConnect,name="testNginxConnect"),
    path('changeNginxConfig',views.changeNginxConfig,name="changeNginxConfig"),
    path('nginx_301',views.nginx301,name="nginx301"),
    path('cloudflareAddDomain',views.cloudflareAddDomain,name="cloudflareAddDomain"),
    path('cloudflareListDomainRecord',views.cloudflareListDomainRecord,name="cloudflareListDomainRecord"),
    path('cloudflareDeleteDomainRecord',views.cloudflareDeleteDomainRecord,name="cloudflareDeleteDomainRecord"),
    path('cloudflareAddDomainRecord',views.cloudflareAddDomainRecord,name="cloudflareAddDomainRecord"),
    path('cloudflareListDomainRateLimits',views.cloudflareListDomainRateLimits,name="cloudflareListDomainRateLimits"),
    path('cloudflareGetDomainNameServer',views.cloudflareGetDomainNameServer,name="cloudflareGetDomainNameServer"),
    path('cloudflareAddDomainRateLimits',views.cloudflareAddDomainRateLimits,name="cloudflareAddDomainRateLimits"),
    path('cloudflareDeleteDomainRateLimits',views.cloudflareDeleteDomainRateLimits,name="cloudflareDeleteDomainRateLimits"),
    path('cloudflareListDomainWAFRules',views.cloudflareListDomainWAFRules,name="cloudflareListDomainWAFRules"),
    path('cloudflareAddDomainWAFRules',views.cloudflareAddDomainWAFRules,name="cloudflareAddDomainWAFRules"),
    path('cloudflareDeleteDomainWAFRules',views.cloudflareDeleteDomainWAFRules,name="cloudflareDeleteDomainWAFRules"),
    path('cloudflareFlushDomainCache',views.cloudflareFlushDomainCache,name="cloudflareFlushDomainCache"),
    path('cloudflareCreateDomainCertificate',views.cloudflareCreateDomainCertificate,name="cloudflareCreateDomainCertificate"),
    path('cloudflareSetDomainAlwaysUseHTTPS',views.cloudflareSetDomainAlwaysUseHTTPS,name="cloudflareSetDomainAlwaysUseHTTPS"),
    path('SIMS_show',views.SIMS_show,name="SIMS_show"),
]

web/templates/web/cloudflare/cloudflareAddDomain.html
{% load static %}
{% include "web/template/base_header.html" %}

<body>
    <form id="ff" action='{% url "web:cloudflareAddDomain" %}' method="post">
        {% csrf_token %}
        <table cellpadding="5">
            <tr>
                <td>domains:</td>
            </tr>
            <tr>
                <td><input class="easyui-textbox" type="text" name="domains" data-options="required:true,multiline:true" value="{{domains}}" style="width:200px;height:200px"></td>
            </tr>
        </table>

        <input type="submit" value="Submit"  />
    </form>
    {% if tipMessage %}
        <div>
            {% for t in tipMessage %}
                <p>{{t}}</p>
            {% endfor %}
        </div>
    {% endif %}
</body>

web/templates/web/cloudflare/cloudflareAddDomainRateLimits.html
{% load static %}
{% include "web/template/base_header.html" %}

<body>
    <form id="ff" action='{% url "web:cloudflareAddDomainRateLimits" %}' method="post">
        {% csrf_token %}
        <table cellpadding="5">
            <tr>
                <td>domains:</td>
            </tr>
            <tr>
                <td><input class="easyui-textbox" type="text" name="domains" data-options="required:true,multiline:true,prompt:'请输入域名，每行一个'"  style="width:200px;height:200px"></td>
            </tr>
        </table>
        <table>
            <tr>
                <td>Name*</td>
                <td>scheme</td>
                <td>method</td>
                <td>url</td>
                <td>threshold</td>
                <td>period</td>
                <td>action</td>
                <td>timeout</td>
                <td>disabled</td>
            </tr>
            <tr>
                <td><input class="easyui-textbox" type="text" name="ruleName" data-options="prompt:'rule name'"></td>
                <td><select class="easyui-combobox" name="scheme" style="width:130px;">
                    <option value="ALL">ALL</option>
                    <option value="HTTPSandHTTP">HTTPS&HTTP</option>
                    <option value="HTTP">HTTP</option>
                    <option value="HTTPS">HTTPS</option>

                </select></td>
                <td><select class="easyui-combobox" name="methods" style="width:130px;">
                    <option value="ALL">ALL</option>
                    <option value="GETandPOST">GET&POST</option>
                    <option value="GET">GET</option>
                    <option value="POST">POST</option>

                </select></td>
                <td><input class="easyui-textbox" type="text" name="url" data-options="prompt:'url'"></td>
                <td><input class="easyui-textbox" type="text" name="threshold" data-options="prompt:'60'" style="width:90px;"></td>
                <td><input class="easyui-textbox" type="text" name="period" data-options="prompt:'60'" style="width:60px;"></td>
                <td><select class="easyui-combobox" name="action" style="width:90px;">
                    <option value="ban">ban</option>
                    <option value="simulate">simulate</option>
                    <option value="challenge">challenge</option>
                    <option value="js_challenge">js_challenge</option>
                </select></td>
                <td><input class="easyui-textbox" type="text" name="timeout" data-options="prompt:'60'" style="width:60px;"></td>
                <td><select class="easyui-combobox" name="disabled" style="width:80px;">
                    <option value="0">False</option>
                    <option value="1">True</option>
                </select></td>
            </tr>
        </table>
        <input type="submit" value="Submit"  />
    </form>
    {% if tipMessage %}
        <div>
            {% for t in tipMessage %}
                <p>{{t}}</p>
            {% endfor %}
        </div>
    {% endif %}
</body>

web/templates/web/cloudflare/cloudflareAddDomainRecord.html
{% load static %}
{% include "web/template/base_header.html" %}

<body>
    <form id="ff" action='{% url "web:cloudflareAddDomainRecord" %}' method="post">
        {% csrf_token %}
        <table cellpadding="5">
            <tr>
                <td>domains:</td>
            </tr>
            <tr>
                <td><input class="easyui-textbox" type="text" name="domains" data-options="required:true,multiline:true,prompt:'请输入域名，每行一个'" style="width:200px;height:200px"></td>
            </tr>
        </table>
        <table>
            <tr>
                <td>Type</td>
                <td>Name*</td>
                <td>Value*</td>
                <td>Proxy status</td>
            </tr>
            <tr>
                <td><select class="easyui-combobox" name="addType" style="width:90px;">
                    <option value="A">A</option>
                    <option value="CNAME">CNAME</option>
                </select></td>
                <td><input class="easyui-textbox" type="text" name="recordName" data-options="prompt:'Use @ for root'"></td>
                <td><input class="easyui-textbox" type="text" name="recordValue" data-options="prompt:'record value'"></td>
                <td><select class="easyui-combobox" name="proxyed" style="width:80px;">
                    <option value="1">True</option>
                    <option value="0">False</option>
                </select></td>
            </tr>

        </table>
        <input type="submit" value="Submit"  />
    </form>
    {% include "web/template/cloudflare/tableShow.html" %}
</body>

web/templates/web/cloudflare/cloudflareAddDomainWAFRules.html
{% load static %}
{% include "web/template/base_header.html" %}

<body>
    <form id="ff" action='{% url "web:cloudflareAddDomainWAFRules" %}' method="post">
        {% csrf_token %}
        <table cellpadding="5">
            <tr>
                <td>domains:</td>
            </tr>
            <tr>
                <td><input class="easyui-textbox" type="text" name="domains" data-options="required:true,multiline:true,prompt:'请输入域名，每行一个'"  style="width:200px;height:200px"></td>
            </tr>
        </table>
        <table>
            <tr>
                <td>Name</td>
                <td>Expression</td>
                <td>Action</td>
            </tr>
            <tr>
                <td><input class="easyui-textbox" type="text" name="ruleName" data-options="prompt:'Rule Name'"></td>
                <td><input class="easyui-textbox" type="text" name="ruleExpression" data-options="prompt:'expression'" style="width:400px"></td>
                <td><select class="easyui-combobox" name="action" style="width:90px;">
                    <option value="Block">Block</option>
                    <option value="JSChallenge">JS Challenge</option>
                    <!--<option value="Challenge_Captcha">Challenge(Captcha)</option>-->
                    <option value="Allow">Allow</option>
                    <option value="Log">Log</option>
                </select></td>
            </tr>
        </table>
        <input type="submit" value="Submit"  />
    </form>
    {% include "web/template/cloudflare/tableShow.html" %}
</body>

web/templates/web/cloudflare/cloudflareDeleteDomainRecord.html
{% load static %}
{% include "web/template/base_header.html" %}

<body>
    <form id="ff" action='{% url "web:cloudflareDeleteDomainRecord" %}' method="post">
        {% csrf_token %}
        <table cellpadding="5">
            <tr>
                <td>domains:</td>
            </tr>
            <tr>
                <td><input class="easyui-textbox" type="text" name="domains" data-options="required:true,multiline:true,prompt:'请输入域名，每行一个'"  style="width:200px;height:200px"></td>
            </tr>
        </table>
        <select class="easyui-combobox" name="deleteType" style="width:200px;">
            <option value="A">A</option>
            <option value="CNAME">CNAME</option>
        </select>
        <input type="submit" value="Submit"  />
    </form>
    {% include "web/template/cloudflare/tableShow.html" %}
</body>

web/templates/web/cloudflare/cloudflareListBase.html
{% load static %}
{% include "web/template/base_header.html" %}

<body>
    <form id="ff" action={{formProcessUrl}} method="post">
        {% csrf_token %}
        <table cellpadding="5">
            <tr>
                <td>domains:</td>
            </tr>
            <tr>
                <td><input class="easyui-textbox" type="text" name="domains" data-options="required:true,multiline:true,prompt:'请输入域名，每行一个'" style="width:200px;height:200px"></td>
            </tr>
        </table>

        <input type="submit" value="Submit"  />
    </form>
    {% include "web/template/cloudflare/tableShow.html" %}
</body>