qqcweb/qqcweb/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('web/',include('web.urls'))
]

qqcweb/web/urls.py
from django.urls import path
from web import views

app_name="web"
urlpatterns = [
    path('',views.index,name="index"),
    path('testConnect/',views.testNginxConnect,name="testNginxConnect"),
    path('changeNginxConfig',views.changeNginxConfig,name="changeNginxConfig"),
    path('nginx_301',views.nginx301,name="nginx301"),
    path('cloudflare_operate',views.cloudflare_operate,name="cloudflare_operate"),
]

qqcweb/web/models.py
from django.db import models

# Create your models here.

qqcweb/web/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
from web.commonTools.tools import *
from web.commonTools.cloudflareClient import *
import logging
logger = logging.getLogger("django")

def index(request):
    return render(request,'web/index.html')

def nginx301(request):
    return render(request,"web/nginx/nginx_301.html",{"formSubmitButtonName": "testNginxConnect","postUrlName": "testNginxConnect"})

def testNginxConnect(request):
    logger.info("request POST: %s" % (str(request.POST)))
    postData = request.POST
    indexTemplateData = {"tipMessage": "",
                         "HostIP": postData["HostIP"],
                         "HostPort": postData["HostPort"],
                         "LoginUser": postData["LoginUser"],
                         "LoginPwd": postData["LoginPwd"],
                         "RootPwd": postData["RootPwd"],
                         "nginxConfigContext": None,
                         ###readonly:配置文件是否可写
                         "readonly": 1,
                         "formSubmitButtonName": "TestConnect",
                         "postUrlName": "testConnect",
                         ###是否可增加新配置文件
                         "addConfigIsAvailable":False
                         }
    if not checkIP(postData["HostIP"]):
        indexTemplateData["tipMessage"] = "IP Address is not valid"
    elif not checkPortIsValid(postData["HostPort"]):
        indexTemplateData["tipMessage"] = "IP Port is not valid"
    else:
        remoteConnect = NginxConfProcessor(postData["HostIP"], postData["HostPort"], postData["LoginUser"],postData["LoginPwd"], postData["RootPwd"], postData["NginxInstallPath"])
        if not remoteConnect.ssh:
            indexTemplateData["tipMessage"] = remoteConnect.connectErrorInfo
        else:
            logger.info("connect to server successfilly")
            retVal = remoteConnect.parser()
            ###分析nginx配置文件返回真，说明nginx配置文件读取成功
            if retVal:
                indexTemplateData["nginxConfigContext"] = remoteConnect.nginxConfigContentDict
                indexTemplateData["formSubmitButtonName"] = "Change Config"
                indexTemplateData["postUrlName"] = "changeNginxConfig"
                indexTemplateData["addConfigIsAvailable"] = True
            ###分析nginx配置文件返回不为真，说明nginx配置文件读取失败
            else:
                indexTemplateData["tipMessage"] = "Error: " + remoteConnect.connectErrorInfo
    return render(request, "web/nginx/nginx_301.html", indexTemplateData)

def changeNginxConfig(request):
    logger.info("request POST: %s" % (str(request.POST)))
    postData = request.POST
    print(postData)
    for key in postData:
        if key in ("HostIP","HostPort","LoginUser","LoginPwd","RootPwd",'NginxInstallPath',"csrfmiddlewaretoken","main"):
            continue
        else:
            remoteConnect = NginxConfProcessor(postData["HostIP"], postData["HostPort"], postData["LoginUser"],postData["LoginPwd"], postData["RootPwd"], postData["NginxInstallPath"])
            remoteConnect.parser()
            ret = remoteConnect.config(key, postData[key])
            if ret:
                respRet = True
                continue
            else:
                respRet = False
                break
    if respRet:
        return HttpResponse("Configure Successfully")
    else:
        return HttpResponse("Configure Failure")

def cloudflare_operate(request):
    print(request.POST)
    postData = request.POST
    templateData = {"tipMessage":'',
                    "domains":'请输入域名，每行一个',
                    }
    ###post数据为空
    if not postData:
        templateData["tipMessage"] = "请输入域名，每行一个"
    ##未输入数据
    elif postData["domains"] == "请输入域名，每行一个":
        templateData["tipMessage"] = "请输入域名，每行一个"
    ###有数据
    else:
        print(postData["domains"])
        # print(type(postData["domains"])) = str
        ##type(domains) = list
        domains = postData["domains"].split("\r\n")

        ##type: str
        ###recordType: A|CNAME|TXT
        recordType = postData["recordType"]
        recordValue = postData["recordValue"]
        ###operateType : ListRecord|AddDomain|AddRecord
        operateType = postData["operateType"]

        ###检查主域名是否合法,有不合法域名立即返回
        for d in domains:
            res = checkMainDomainIsValid(d)
            print("check domain %s result: %s" %(d,res))
            if not res:
                templateData["tipMessage"] = "%s is not valid,pls check" %(d)
                return render(request, "web/cloudflare/cloudflareListBase.html", templateData)


        cloudflareClient = CloudflareClient("helaowang@gmail.com","799bdf658832da5b74be6c0a4a2b35d3a43e3")
        cf_zoneID = cloudflareClient.getZoneID()
        cf_userID = cloudflareClient.getUserID()
        ###多个账号得情况下，需确认具体得账号
        cf_account = cloudflareClient.getAccountID()

        ###列出记录
        if operateType == "ListRecord":
            for d in domains:
                ##获取domainZoneID
                domainZoneID = cloudflareClient.getDomainZoneID(d)
                print("domainZoneID=%s" %domainZoneID)
                ##获取记录
                domainRecordList = cloudflareClient.getDomainRecordList(domainZoneID)
                print("domainRecordList for domain %s : %s" %(d,domainRecordList))
        elif operateType == "AddDomain":
            pass
        elif operateType == "AddRecord":
            pass
        else:
            pass
        templateData["tipMessage"] = "ok"
    return render(request,"web/cloudflare/cloudflareListBase.html",templateData)

qqcweb/web/templates/web/cloudflare/cloudflare_operate.html
{% load static %}
{% include "web/template/base_header.html" %}

<body>
    <form id="ff" action='{% url "web:cloudflare_operate" %}' method="post">
        {% csrf_token %}
        <table cellpadding="5">
            <tr>
                <td>domains:</td>
            </tr>
            <tr>
                <td><input class="easyui-textbox" type="text" name="domains" data-options="required:true,multiline:true" value="{{domains}}" style="width:200px;height:200px"></td>
            </tr>
        </table>
        <select class="easyui-combobox" name="recordType" style="width:100px;">
            <option value="A">A</option>
            <option value="CNAME">CNAME</option>
            <option value="TXT">TXT</option>
        </select>
        <input class="easyui-textbox" type="text" name="recordValue" data-options="required:true" value="IP v4 address">
        <br/><br/>
        <select class="easyui-combobox" name="operateType" style="width:200px;">
            <option value="ListRecord">列出记录</option>
            <option value="AddDomain">添加域名</option>
            <option value="AddRecord">添加记录</option>
        </select>
        <input type="submit" value="Submit"  />
    </form>
    {% if tipMessage %}
        <div>
             {{tipMessage}}
        </div>
    {% endif %}
</body>

qqcweb/web/templates/web/common/js/associationMenuToTab.html
<script type="text/javascript">
	$(function(){
		$("a[title]").click(function(){
			var text = $(this).text();
			var href = $(this).attr("title");
			//判断当前右边是否已有相应的tab
			if($("#tt").tabs("exists", text)) {
				$("#tt").tabs("select", text);
			} else {
				//如果没有则创建一个新的tab，否则切换到当前tag
				$("#tt").tabs("add",{
					title:text,
					closable:true,
					content:'<iframe title=' + text + ' src=' + href + ' frameborder="0" width="100%" height="100%" />',
					//href:默认通过url地址加载远程的页面，但是仅仅是body部分
					//href:'send_category_query.action'
					tools:[{
					    iconCls:'icon-reload',
					    handler:function(){

					    },
					}]
				});
			}

		});
	});
</script>

qqcweb/web/templates/web/nginx/nginx_301.html
{% load static %}
{% include "web/template/base_header.html" %}

{% if postUrlName == "testNginxConnect" %}
<form action='{% url "web:testNginxConnect" %}' method="post">
{% elif postUrlName == "changeNginxConfig" %}
<form action='{% url "web:changeNginxConfig" %}' method="post">
{% endif %}
    {% csrf_token %}
    <!--<p>HostIP: <input type="text" name="HostIP" value="{{HostIP}}"/></p>-->
    <!--<p>HostPort: <input type="text" name="HostPort" value="{{HostPort}}"/></p>-->
    <!--<p>LoginUser: <input type="text" name="LoginUser" value="{{LoginUser}}"/></p>-->
    <!--<p>LoginPwd: <input type="password" name="LoginPwd" value="{{LoginPwd}}"/></p>-->
    <!--<p>RootPwd: <input type="password" name="RootPwd" value="{{RootPwd}}"/></p>-->
    <!--<p>NginxInstallPath: <input type="text" name="NginxInstallPath" value="/usr/local/gacp/nginx/"/></p>-->
    <div><label style="display:inline-block;width:100px;">HostIP: </label><input class="easyui-validatebox" data-options="required:true" type="text" name="HostIP" value="10.64.36.52"/></div>
    <div><label style="display:inline-block;width:100px;">HostPort: </label><input class="easyui-validatebox" data-options="required:true" type="text" name="HostPort" value="22"/></div>
    <div><label style="display:inline-block;width:100px;">LoginUser: </label><input class="easyui-validatebox" data-options="required:true" type="text" name="LoginUser" value="qqc"/></div>
    <div><label style="display:inline-block;width:100px;">LoginPwd: </label><input class="easyui-validatebox" data-options="required:true" type="password" name="LoginPwd" value="Qqc@123"/></div>
    <div><label style="display:inline-block;width:100px;">RootPwd: </label><input class="easyui-validatebox" data-options="required:true" type="password" name="RootPwd" value="Qqc@123"/></div>
    <div><label style="display:inline-block;width:100px;">NginxPath: </label><input class="easyui-validatebox" data-options="required:true" type="text" name="NginxInstallPath" value="/usr/local/nginx/"/></div>
    <input type="submit" value="{{formSubmitButtonName}}"  />
    {% if addConfigIsAvailable %}
        <a title="addconfig" id="addconfig" href="#" class="easyui-linkbutton" data-options="iconCls:'icon-add'">增加配置</a>
    {% endif %}

    {% if nginxConfigContext %}
        <div id="nginxConfigZone">
        {% for name,content in nginxConfigContext.items %}

                <p>{{name}}</p>
                {% with c=content %}
                    <textarea name="{{name}}" style="width:50%;height:220px">{% for line in c %}{{line}}{% endfor %}</textarea>
                {% endwith %}
        </div>

        {% endfor %}
    {%endif%}

</form>
    {% if tipMessage %}
        <div id="win" class="easyui-window" title="提示消息" style="width:600px;height:400px" data-options="iconCls:'icon-save',modal:true">
             {{tipMessage}}
        </div>
    {% endif %}

    <script type="text/javascript">
        $(function(){
            $("a[title]").click(function(){
                var unixT = Date.parse(new Date())/1000;
                $("#nginxConfigZone").append('<p><input class="easyui-validatebox" data-options="required:true" type="text" name="' + unixT + '_filename" /></p><textarea name="' + unixT + '_filecontent" style="width:50%;height:220px"></textarea>');

            });
        });

    </script>
</form>

qqcweb/web/templates/web/template/base_header.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>{% block pageTitle %}QQC WEB{% endblock%}</title>

    <link rel="stylesheet" type="text/css" href="{% static 'jquery-easyui-1.7.0/themes/default/easyui.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'jquery-easyui-1.7.0/themes/icon.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'inputCss.css' %}">

	<script type="text/javascript" src="{% static 'jquery-easyui-1.7.0/jquery.min.js' %}">



    </script>
	<script type="text/javascript" src="{% static 'jquery-easyui-1.7.0/jquery.easyui.min.js' %}"></script>
</head>

qqcweb/web/templates/web/template/cloudflare/template_cloudflare.html
<ul class="easyui-tree">
    <li>
        <a href="#" style="text-decoration: none;" title="cloudflare_operate">Operate</a>
    </li>
</ul>
<!--关联菜单和tab内容得js脚本-->
{% include "web/common/js/associationMenuToTab.html" %}

qqcweb/web/templates/web/template/nginx/template_nginx.html
<ul class="easyui-tree">
    <li>
        <a href="#" style="text-decoration: none;" title="nginx_301">nginx 301</a>
    </li>
    <li>
        <a href="#" style="text-decoration: none;" title="nginx_ssl">nginx ssl</a>
    </li>
</ul>
<!--关联菜单和tab内容得js脚本-->
{% include "web/common/js/associationMenuToTab.html" %}